<?php 
if(class_exists('Vtiger_Module_Model')) {
	$moduleModel = Vtiger_Module_Model::getInstance('ModComments');
	if(is_object($moduleModel)) {
		$mTabid = $moduleModel->getId();

		if($mTabid) {
			$report_array_json = '{"its4you_reports4you_selectcolumn":[["@reportid",0,"vtiger_modcomments:commentcontent:ModComments_Comment:commentcontent:V"],["@reportid",1,"vtiger_modcomments:customer:ModComments_Customer:customer:V"],["@reportid",2,"vtiger_modcomments:userid:ModComments_UserId:userid:V"],["@reportid",3,"vtiger_modcomments:reasontoedit:ModComments_ReasonToEdit:reasontoedit:V"],["@reportid",4,"vtiger_crmentity:smcreatorid:ModComments_Created By:created_user_id:V"],["@reportid",5,"vtiger_crmentity:smownerid:ModComments_Assigned To:assigned_user_id:V"],["@reportid",6,"vtiger_modcomments:related_to:ModComments_Related To:related_to:V"],["@reportid",7,"vtiger_crmentity:createdtime:ModComments_Created Time:createdtime:DT"],["@reportid",8,"vtiger_crmentity:modifiedtime:ModComments_Modified Time:modifiedtime:DT"],["@reportid",9,"vtiger_modcomments:parent_comments:ModComments_Related To Comments:parent_comments:V"]],"its4you_reports4you_summaries":[["@reportid",0,"vtiger_crmentity:crmid:Potentials_LBL_RECORDS:Potentials_count:V:COUNT"]],"its4you_reports4you_summaries_orderby":["@reportid",0,"none","ASC"],"its4you_reports4you_labels":[["@reportid","SC","vtiger_modcomments:commentcontent:ModComments_Comment:commentcontent:V","Comment"],["@reportid","SC","vtiger_modcomments:customer:ModComments_Customer:customer:V","Customer"],["@reportid","SC","vtiger_modcomments:userid:ModComments_UserId:userid:V","UserId"],["@reportid","SC","vtiger_modcomments:reasontoedit:ModComments_ReasonToEdit:reasontoedit:V","ReasonToEdit"],["@reportid","SC","vtiger_crmentity:smcreatorid:ModComments_Created By:created_user_id:V","Created By"],["@reportid","SC","vtiger_crmentity:smownerid:ModComments_Assigned To:assigned_user_id:V","Assigned To"],["@reportid","SC","vtiger_modcomments:parent_comments:ModComments_Related To Comments:parent_comments:V","Related To"],["@reportid","SC","vtiger_crmentity:createdtime:ModComments_Created Time:createdtime:DT","Created Time"],["@reportid","SC","vtiger_crmentity:modifiedtime:ModComments_Modified Time:modifiedtime:DT","Modified Time"]],"its4you_reports4you":["@reportid","ITS4You: Comments By Related To","","2","summaries_w_details",0,20,20],"its4you_reports4you_modules":["@reportid","ModComments",""],"its4you_reports4you_sortcol":[[1,"@reportid","vtiger_modcomments:related_to:ModComments_Related To:related_to:V","Ascending","rows",null,null],[2,"@reportid","none","Ascending","rows",null,null],[3,"@reportid","none","Ascending","rows",null,null],[4,"@reportid","none","ASC","","",""]],"its4you_reports4you_datefilter":["@reportid",null,null,null,null],"its4you_reports4you_settings":["@reportid","1","public"]}';
		}
	}
}